title: Bytes and Humans
email: your-email@example.com
description: >-
  People-centered creative technical projects
#baseurl: ""
url: "https://bytesandhumans.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bytesandhumans
markdown: kramdown

plugins:
  - jekyll-feed

copy:
  assets:
     - "assets/**/*"
  dist: "_site/assets"
  notification: "Running Copy"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.lock.json
  - package.json
  - webpack.config.babel.js
  - src
  - .editorconfig
  - .eslintignore
  - .eslintrc.js
